# Bengali
VOTERS_NAME = 'নাম'
HUSBANDS_NAME = 'স্বামীর নাম'
FATHERS_NAME = 'पপিতার নাম'
FATHERS_NAME2 = 'পিতার নাম'
MOTHERS_NAME = 'মার নাম'
MOTHERS_NAME2 = 'মাতার নাম'
OTHERS_NAME = 'অন্যান্যর নাম'
AGE = 'বয়স'
GENDER = 'লিঙ্গ'
HOUSE_COUNT = 'বাড়ীর নং'
FEMALE = 'স্ত্রী'
MALE = 'পুং'
BOOTH_NAME_COUNT = 'पভাগ নং ,নাম'
